const projects = [
    { "id": 1, "name": "Heart Animation", "folder": "Project 1 heart animation", "description": "A simple animation of a beating heart using CSS and JavaScript." },
    { "id": 2, "name": "Auto Text Effect", "folder": "Project 2 auto text", "description": "Automatically displays text letter by letter with a typing effect." },
    { "id": 3, "name": "Mini Calendar", "folder": "Project 3 mini calender", "description": "A small interactive calendar that displays the current month and date." },
    { "id": 4, "name": "Button Ripple Effect", "folder": "Project 4 button ripple", "description": "Adds a ripple effect when a button is clicked, enhancing UI interaction." },
    { "id": 5, "name": "Random Image Generator", "folder": "Project 5 random image", "description": "Generates and displays random images from an API or a predefined set." },
    { "id": 6, "name": "Dark Mode Toggle", "folder": "Project 6 dark mode", "description": "Allows users to toggle between light and dark themes for better UI accessibility." },
    { "id": 7, "name": "Testimonial Slider", "folder": "Project 7 Testimonial slider", "description": "Displays multiple testimonials with smooth sliding transitions." },
    { "id": 8, "name": "Real-time Character Counter", "folder": "Project 8 Real time characte counter", "description": "Counts characters as users type in a text area, useful for input limits." },
    { "id": 9, "name": "Digital Clock", "folder": "Project 9 digital clock", "description": "Displays a real-time digital clock that updates every second." },
    { "id": 10, "name": "Double Landing Page", "folder": "Project 10 double landing page", "description": "A landing page with a split-screen design, showing two different sections." },
    { "id": 11, "name": "Random Color Generator", "folder": "Project 11 random color generator", "description": "Generates random colors with their HEX codes on button click." },
    { "id": 12, "name": "Rotating Image Gallery", "folder": "Project 12 Rotating Image Gallery", "description": "An image gallery with smooth rotating transition effects." },
    { "id": 13, "name": "Animated Search Bar", "folder": "Project 13 animated search bar", "description": "A stylish search bar that expands when clicked." },
    { "id": 14, "name": "Loan Calculator", "folder": "Project 14 loan calculator", "description": "Calculates monthly loan payments based on amount, interest, and duration." },
    { "id": 15, "name": "New Year Countdown", "folder": "Project 15 new year countdown", "description": "Displays a countdown timer for the New Year." },
    { "id": 16, "name": "Pomodoro Timer", "folder": "Project 16 pomodoro timer", "description": "A time management tool based on the Pomodoro technique." },
    { "id": 17, "name": "Age Calculator", "folder": "Project 17 age calculator", "description": "Calculates a user's age based on the input birthdate." },
    { "id": 18, "name": "Project Statistics", "folder": "Project 18 project statistics", "description": "Displays statistics and progress of various projects dynamically." },
    { "id": 19, "name": "Video Trailer Popup", "folder": "Project 19 video trailer popup", "description": "Displays a popup with a video trailer when clicked." },
    { "id": 20, "name": "Drum Kit", "folder": "Project 20 drum kits", "description": "A virtual drum kit where users can play sounds by clicking or using keys." },
    { "id": 21, "name": "Clock", "folder": "Project 21 clock", "description": "A simple analog or digital clock showing the current time." },
    { "id": 22, "name": "Temperature Converter", "folder": "Project 22 temperature convertor", "description": "Converts temperatures between Celsius, Fahrenheit, and Kelvin." },
    { "id": 23, "name": "BMI Calculator", "folder": "Project 23 BMI calculator", "description": "Calculates Body Mass Index (BMI) based on weight and height." },
    { "id": 24, "name": "Sticky Navbar", "folder": "Project 24 sticky navbar", "description": "A navigation bar that remains fixed at the top while scrolling." },
    { "id": 25, "name": "Random Emoji Generator", "folder": "Project 25 random emoji", "description": "Generates random emojis on button click." },
    { "id": 26, "name": "Tip Calculator", "folder": "Project 26 tip calculator", "description": "Calculates tip amounts based on bill total and percentage." },
    { "id": 27, "name": "Loading Bar", "folder": "Project 27 loading bar", "description": "A progress bar that animates to indicate loading status." },
    { "id": 28, "name": "Background Image Scroll Effect", "folder": "Project 28 background image scroll effect", "description": "Applies a parallax scrolling effect to background images." },
    { "id": 29, "name": "Mouse Event Tracker", "folder": "Project 29 mouse event", "description": "Tracks and displays mouse movement coordinates in real-time." },
    { "id": 30, "name": "Dice Roll Simulator", "folder": "Project 30 dice roll simulator", "description": "Simulates rolling a dice and displays the result randomly." }
];

console.log(projects[0]); // Example: Displaying the first project in console
export default projects;
